/**
* @author Gurditta Garg
* @date March 2016
* @description This is class for Constants
*/

global class Constants {
    global static final String NEWLINE = '\n';
    global static final String COMMA = ',';
    global static final String SPACE = ' ';
    global static final String EMPTY = '';
    global static final String COLON = ':';
    global static final String EQUALS_SIGN = '=';
    global static final String HASH = '#';
    global static final String HI = 'Hi';
    global static final String EMS = 'EMS';
    global static final String CN_EQUALS = 'cn=';
    global static final String EMS_EXTERNAL_USER = 'EMS External User';
    global static final String WELCOME1 = 'welcome1';
    global static final String APPROVED = 'Approved';
    global static final String WINFIELD = 'Winfield';
    global static final String PURINA = 'Purina';
    global static final String LOL = 'LOL';
    global static final String CORPORATE = 'Corporate';
    global static final String FAILED = 'FAILED';
    global static final String TASK_STATUS = 'Task Status';
    global static final String CSV = '.csv';
    global static final String BLOB_ENCODE = 'ISO-8859-1';
    global static final String PROCESSING = 'Processing';
    global static final String QUEUED = 'Queued';
    global static final String ISMASSLOADED = 'TRUE';
    global static final String STATUS = 'Validated';
    global static final String PENDINGACCOUNT = 'Pending Registrations';
}