public with sharing class EMSConstants {

	public static final String CREATUSER_ACT = 'CREATEUSER';
	public static final String UPDATECONTACT_ACT = 'UPDATECONTACt';
	public static final String CHANGEPASSWORD_ACT = 'CHANGEPASSWORD';
	public static final String DISABLEUSER_ACT = 'DISABLEUSER';
	public static final String UPDATE_OPERATION = 'Update';
	public static final String CART_FG_RT ='Fine_Grained'; //cart entitlement fine grained record type developername
	public static final String CART_CG_RT = 'Role'; // cart entitlement coarse grained record type developername
	public static final String REQ_FIELD_TEMPLATE = 'Label: Value<br>';
	public static final String REQ_FG_TEMPLATE ='Account: Name, AcctNo, Address<br>';
	public static final String CART_FG_LABEL ='Fine Grained'; //cart entitlement fine grained record type developername
	public static final String CART_CG_LABEL = 'Role'; // cart entitlement coarse grained record type developername
	public static final String DELEGATED_ADMIN_APPCODE = 'emsdelegatedadmin';



}