/**
* @author Gurditta Garg
* @date March 2016
* @description This class is for feeding User Wrappers to batch for Mass Upload Functionality
*/

global class MassUploadNewUserFeeder {
/*implements Iterator<UserWrapper>, Iterable<UserWrapper> {
    List<UserWrapper> source;
    
    global Iterator<UserWrapper> iterator() {
        return this;
    }
    
    public MassUploadNewUserFeeder(List<UserWrapper> source) {
        this.source = source;
    }
    
    public UserWrapper next() {
        return source.remove(0);
    }
    
    global boolean hasNext() {
        return source!=null && !source.isempty();
    }*/
}