public class UserWrapper {
    /*
    public User usr{get;set;}
    public Contact con{get;set;}
    public Account acc{get;set;}
    public String businessUnit{get;set;}
    public String mgrName{get;set;}
    public String mgrEmail{get;set;}
    public String mgrPhone{get;set;}
    public String accNum{get;set;}
    
    public UserWrapper(User usr, Contact con, Account acc, String businessUnit, String mgrName, String mgrEmail, String mgrPhone, String accNum) {
        this.usr = usr;
        this.con = con;
        this.acc = acc;
        this.businessUnit = businessUnit;
        this.mgrName = mgrName;
        this.mgrEmail = mgrEmail;
        this.mgrPhone = mgrPhone;
        this.accNum = accNum;
    }*/
}